name: vent
description: Given app that looks on the bright side
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  dart_mappable: ^3.1.1
  desktop_window: ^0.4.0
  dio: ^5.1.2
  disposebag: ^1.5.1
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  expandable: ^5.0.1
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_flavor: ^3.1.1
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  getwidget: ^3.1.1
  go_router: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.2
  intl: any
  json_annotation: ^4.8.1
  localizely_sdk: ^2.5.0
  logging: ^1.2.0
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.5
  retrofit: ^4.0.1
  rxdart: ^0.27.7
  sms_autofill: ^2.3.0
  talker: ^3.0.0
  talker_dio_logger: ^2.1.2
  talker_flutter: ^3.1.5

dev_dependencies:
  build_runner: ^2.4.5
  dart_mappable_builder: ^3.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1
  test: ^1.24.1
  very_good_analysis: ^5.0.0+1

flutter_native_splash:
  color: "#E01859"
  image: assets/splash/image.png

  android_12:
    color: "#E01859"

  web: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Gantari
      fonts:
        - asset: assets/fonts/Gantari.ttf
          style: normal
